[project]
name = "openai-agents-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.5.5",
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "openai>=1.75.0",
    "openai-agents[voice]>=0.0.11",
    "pydantic>=2.11.3",
    "sounddevice>=0.5.1",
    "twilio>=9.5.2",
]
